server:
  port: 9100

spring:
  application:
    name: themoment-team-api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka