server:
  port: 9201

spring:
  application:
    name: candy-service-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka